name: yangi_tv_new
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.1.3+66

environment:
  sdk: '>=3.5.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio: ^5.4.2+1
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0
  flutter_carousel_slider: ^1.1.0
  carousel_slider: ^5.0.0
  blur: ^4.0.0
  video_player: ^2.8.6
  keep_screen_on: ^3.0.0
  url_launcher: ^6.2.6
  package_info_plus: ^8.0.0
  share_plus: ^10.1.2
  audio_video_progress_bar: ^2.0.2
  flutter_prevent_screen_capture: ^0.0.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.0
  device_info_plus: ^11.1.1
  fancy_shimmer_image: ^2.0.3
  youtube_player_flutter: ^9.0.1
  sqflite: ^2.3.3+1
  fluttertoast: ^8.2.4
  collection: ^1.18.0
  syncfusion_flutter_sliders: ^27.2.3
  cast: ^2.0.0
  intl: ^0.19.0
  background_downloader: ^8.8.0
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  in_app_review: ^2.0.9
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  like_button: ^2.0.5
  safe_device: ^1.1.7
  encrypt: ^5.0.3
  get_radio_version_plugin: ^1.0.0
  in_app_update: ^4.2.2
  sms_autofill: ^2.3.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  rename: ^3.0.2
  installed_apps: ^1.5.2
  get_it: ^8.0.2
  process_run: ^1.2.2+1
  jailbreak_root_detection: ^1.1.5
  root_jailbreak_sniffer: ^1.0.9
  workmanager: ^0.5.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher/launcher_logo.png"
  image_path_ios: "assets/images/launcher/launcher_logo_ios.png"
  adaptive_icon_foreground: "assets/images/launcher/logo_foreground.png"
  adaptive_icon_background: "#000000"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/landing/
    - assets/google_fonts/
    - assets/icons/auth/
    - assets/icons/navigation/
    - assets/icons/search/
    - assets/icons/watch/
    - assets/icons/profile/
    - assets/icons/social/
    - assets/icons/session/
    - assets/icons/payment/
    - assets/icons/tariff/
    - assets/icons/comment/
    - assets/icons/promocode/
    - assets/icons/player/
    - assets/icons/download/
    - assets/icons/favorites/
    - assets/icons/player/quality/
    - assets/images/
    - assets/images/landing/images/
    - assets/images/
    - assets/numbers/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
